name: Guillaume Vincent
description: Site personnel de Guillaume Vincent
url: http://guillaumevincent.com
pygments: True
excerpt_separator: <!--more-->
encoding: utf-8
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
