# Site settings
title: Guillaume Vincent
description: Hello I'm Guillaume, I'm a software craftsman and I work for Red Hat remotely from France. I love everything about computer science, clean code, software architecture, design, user experience, scuba diving, golf, cats, and so much more....
baseurl: ""
url: "https://guillaumevincent.com"

# Build settings
markdown: kramdown
highlighter: rouge
exclude: [node_modules, assets, package.json, README.md]
excerpt_separator: 
