name: The Personal Blog of Guillaume Vincent
description: My Personal blog where i can put some of my thoughts together
url: http://localhost:4000/
pygments: True
exclude: [bower_components]
excerpt_separator: <!--more-->