name: Guillaume Vincent
description: Site personnel de Guillaume Vincent
url: http://127.0.0.1:4000
highlighter: pygments
excerpt_separator: <!--more-->
encoding: utf-8
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
